name: contentsquare
packages:
  - packages/**

scripts:
  lint:all:
    run: melos run analyze
    description: Run all static analysis checks

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  clean:
    run: |
      melos exec -c 5 -- \
        flutter clean
    description: |
      Run `flutter clean` in all packages.

  test:
    run: |
      melos exec -c 5 --fail-fast -- \
        "flutter test --no-pub --coverage"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
