// Autogenerated from Pigeon (v3.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FLTType) {
  FLTTypeString = 0,
  FLTTypeInteger = 1,
  FLTTypeNumericstring = 2,
  FLTTypeExpirydate = 3,
  FLTTypeBooleanEnum = 4,
  FLTTypeDate = 5,
};

typedef NS_ENUM(NSUInteger, FLTPreferredInputType) {
  FLTPreferredInputTypeIntegerKeyboard = 0,
  FLTPreferredInputTypeStringKeyboard = 1,
  FLTPreferredInputTypePhoneNumberKeyboard = 2,
  FLTPreferredInputTypeEmailAddressKeyboard = 3,
  FLTPreferredInputTypeDateKeyboard = 4,
};

typedef NS_ENUM(NSUInteger, FLTListType) {
  FLTListTypeText = 0,
  FLTListTypeList = 1,
  FLTListTypeCurrency = 2,
  FLTListTypeDate = 3,
  FLTListTypeBooleanEnum = 4,
};

typedef NS_ENUM(NSUInteger, FLTPaymentProductFieldDisplayElementType) {
  FLTPaymentProductFieldDisplayElementTypeInteger = 0,
  FLTPaymentProductFieldDisplayElementTypeString = 1,
  FLTPaymentProductFieldDisplayElementTypeCurrency = 2,
  FLTPaymentProductFieldDisplayElementTypePercentage = 3,
  FLTPaymentProductFieldDisplayElementTypeUri = 4,
};

typedef NS_ENUM(NSUInteger, FLTValidationType) {
  FLTValidationTypeExpirationDate = 0,
  FLTValidationTypeEmailAdress = 1,
  FLTValidationTypeFixedList = 2,
  FLTValidationTypeIban = 3,
  FLTValidationTypeLength = 4,
  FLTValidationTypeLuhn = 5,
  FLTValidationTypeRange = 6,
  FLTValidationTypeRegularExpression = 7,
  FLTValidationTypeType = 8,
  FLTValidationTypeTermsAndConditions = 9,
};

@class FLTSessionRequest;
@class FLTSessionResponse;
@class FLTPaymentContextRequest;
@class FLTGetPaymentProductRequest;
@class FLTPaymentContextResponse;
@class FLTBasicPaymentProduct;
@class FLTDisplayHintsPaymentItem;
@class FLTPaymentProduct;
@class FLTPaymentProductField;
@class FLTDisplayHintsProductFields;
@class FLTTooltip;
@class FLTFormElement;
@class FLTValueMap;
@class FLTPaymentProductFieldDisplayElement;
@class FLTDataRestrictions;
@class FLTAbstractValidationRule;
@class FLTPaymentRequest;
@class FLTPreparedPaymentRequest;

@interface FLTSessionRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithClientSessionId:(NSString *)clientSessionId
    customerId:(NSString *)customerId
    clientApiUrl:(NSString *)clientApiUrl
    assetBaseUrl:(NSString *)assetBaseUrl
    environmentIsProduction:(NSNumber *)environmentIsProduction
    applicationIdentifier:(NSString *)applicationIdentifier;
@property(nonatomic, copy) NSString * clientSessionId;
@property(nonatomic, copy) NSString * customerId;
@property(nonatomic, copy) NSString * clientApiUrl;
@property(nonatomic, copy) NSString * assetBaseUrl;
@property(nonatomic, strong) NSNumber * environmentIsProduction;
@property(nonatomic, copy) NSString * applicationIdentifier;
@end

@interface FLTSessionResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSessionId:(NSString *)sessionId;
@property(nonatomic, copy) NSString * sessionId;
@end

@interface FLTPaymentContextRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSessionId:(NSString *)sessionId
    amountValue:(NSNumber *)amountValue
    currencyCode:(NSString *)currencyCode
    countryCode:(NSString *)countryCode
    isRecurring:(NSNumber *)isRecurring;
@property(nonatomic, copy) NSString * sessionId;
@property(nonatomic, strong) NSNumber * amountValue;
@property(nonatomic, copy) NSString * currencyCode;
@property(nonatomic, copy) NSString * countryCode;
@property(nonatomic, strong) NSNumber * isRecurring;
@end

@interface FLTGetPaymentProductRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSessionId:(NSString *)sessionId
    paymentProductId:(NSString *)paymentProductId
    amountValue:(NSNumber *)amountValue
    currencyCode:(NSString *)currencyCode
    countryCode:(NSString *)countryCode
    isRecurring:(NSNumber *)isRecurring;
@property(nonatomic, copy) NSString * sessionId;
@property(nonatomic, copy) NSString * paymentProductId;
@property(nonatomic, strong) NSNumber * amountValue;
@property(nonatomic, copy) NSString * currencyCode;
@property(nonatomic, copy) NSString * countryCode;
@property(nonatomic, strong) NSNumber * isRecurring;
@end

@interface FLTPaymentContextResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithBasicPaymentProduct:(NSArray<FLTBasicPaymentProduct *> *)basicPaymentProduct;
@property(nonatomic, strong) NSArray<FLTBasicPaymentProduct *> * basicPaymentProduct;
@end

@interface FLTBasicPaymentProduct : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    paymentMethod:(nullable NSString *)paymentMethod
    paymentProductGroup:(nullable NSString *)paymentProductGroup
    minAmount:(nullable NSNumber *)minAmount
    maxAmount:(nullable NSNumber *)maxAmount
    allowsRecurring:(nullable NSNumber *)allowsRecurring
    allowsTokenization:(nullable NSNumber *)allowsTokenization
    usesRedirectionTo3rdParty:(nullable NSNumber *)usesRedirectionTo3rdParty
    displayHints:(nullable FLTDisplayHintsPaymentItem *)displayHints;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy, nullable) NSString * paymentMethod;
@property(nonatomic, copy, nullable) NSString * paymentProductGroup;
@property(nonatomic, strong, nullable) NSNumber * minAmount;
@property(nonatomic, strong, nullable) NSNumber * maxAmount;
@property(nonatomic, strong, nullable) NSNumber * allowsRecurring;
@property(nonatomic, strong, nullable) NSNumber * allowsTokenization;
@property(nonatomic, strong, nullable) NSNumber * usesRedirectionTo3rdParty;
@property(nonatomic, strong, nullable) FLTDisplayHintsPaymentItem * displayHints;
@end

@interface FLTDisplayHintsPaymentItem : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithDisplayOrder:(NSNumber *)displayOrder
    label:(NSString *)label
    logoUrl:(NSString *)logoUrl;
@property(nonatomic, strong) NSNumber * displayOrder;
@property(nonatomic, copy) NSString * label;
@property(nonatomic, copy) NSString * logoUrl;
@end

@interface FLTPaymentProduct : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    paymentMethod:(nullable NSString *)paymentMethod
    paymentProductGroup:(nullable NSString *)paymentProductGroup
    minAmount:(nullable NSNumber *)minAmount
    maxAmount:(nullable NSNumber *)maxAmount
    allowsRecurring:(nullable NSNumber *)allowsRecurring
    allowsTokenization:(nullable NSNumber *)allowsTokenization
    usesRedirectionTo3rdParty:(nullable NSNumber *)usesRedirectionTo3rdParty
    displayHints:(nullable FLTDisplayHintsPaymentItem *)displayHints
    fields:(NSArray<FLTPaymentProductField *> *)fields;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy, nullable) NSString * paymentMethod;
@property(nonatomic, copy, nullable) NSString * paymentProductGroup;
@property(nonatomic, strong, nullable) NSNumber * minAmount;
@property(nonatomic, strong, nullable) NSNumber * maxAmount;
@property(nonatomic, strong, nullable) NSNumber * allowsRecurring;
@property(nonatomic, strong, nullable) NSNumber * allowsTokenization;
@property(nonatomic, strong, nullable) NSNumber * usesRedirectionTo3rdParty;
@property(nonatomic, strong, nullable) FLTDisplayHintsPaymentItem * displayHints;
@property(nonatomic, strong) NSArray<FLTPaymentProductField *> * fields;
@end

@interface FLTPaymentProductField : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    type:(FLTType)type
    displayHints:(nullable FLTDisplayHintsProductFields *)displayHints
    dataRestrictions:(nullable FLTDataRestrictions *)dataRestrictions;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, assign) FLTType type;
@property(nonatomic, strong, nullable) FLTDisplayHintsProductFields * displayHints;
@property(nonatomic, strong, nullable) FLTDataRestrictions * dataRestrictions;
@end

@interface FLTDisplayHintsProductFields : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAlwaysShow:(NSNumber *)alwaysShow
    obfuscate:(NSNumber *)obfuscate
    displayOrder:(NSNumber *)displayOrder
    label:(NSString *)label
    placeholderLabel:(NSString *)placeholderLabel
    link:(NSString *)link
    mask:(NSString *)mask
    preferredInputType:(FLTPreferredInputType)preferredInputType
    tooltip:(FLTTooltip *)tooltip
    formElement:(FLTFormElement *)formElement;
@property(nonatomic, strong) NSNumber * alwaysShow;
@property(nonatomic, strong) NSNumber * obfuscate;
@property(nonatomic, strong) NSNumber * displayOrder;
@property(nonatomic, copy) NSString * label;
@property(nonatomic, copy) NSString * placeholderLabel;
@property(nonatomic, copy) NSString * link;
@property(nonatomic, copy) NSString * mask;
@property(nonatomic, assign) FLTPreferredInputType preferredInputType;
@property(nonatomic, strong) FLTTooltip * tooltip;
@property(nonatomic, strong) FLTFormElement * formElement;
@end

@interface FLTTooltip : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithImage:(NSString *)image
    label:(NSString *)label;
@property(nonatomic, copy) NSString * image;
@property(nonatomic, copy) NSString * label;
@end

@interface FLTFormElement : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(FLTListType)type
    valueMapping:(NSArray<FLTValueMap *> *)valueMapping;
@property(nonatomic, assign) FLTListType type;
@property(nonatomic, strong) NSArray<FLTValueMap *> * valueMapping;
@end

@interface FLTValueMap : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValue:(NSString *)value
    displayElements:(NSArray<FLTPaymentProductFieldDisplayElement *> *)displayElements;
@property(nonatomic, copy) NSString * value;
@property(nonatomic, strong) NSArray<FLTPaymentProductFieldDisplayElement *> * displayElements;
@end

@interface FLTPaymentProductFieldDisplayElement : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    type:(FLTPaymentProductFieldDisplayElementType)type
    value:(NSString *)value;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, assign) FLTPaymentProductFieldDisplayElementType type;
@property(nonatomic, copy) NSString * value;
@end

@interface FLTDataRestrictions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIsRequired:(NSNumber *)isRequired
    validationRules:(NSArray<FLTAbstractValidationRule *> *)validationRules;
@property(nonatomic, strong) NSNumber * isRequired;
@property(nonatomic, strong) NSArray<FLTAbstractValidationRule *> * validationRules;
@end

@interface FLTAbstractValidationRule : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithMessageId:(NSString *)messageId
    type:(FLTValidationType)type;
@property(nonatomic, copy) NSString * messageId;
@property(nonatomic, assign) FLTValidationType type;
@end

@interface FLTPaymentRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValues:(NSDictionary<NSString *, NSString *> *)values
    paymentProductId:(NSString *)paymentProductId
    tokenize:(NSNumber *)tokenize
    sessionId:(NSString *)sessionId;
@property(nonatomic, strong) NSDictionary<NSString *, NSString *> * values;
@property(nonatomic, copy) NSString * paymentProductId;
@property(nonatomic, strong) NSNumber * tokenize;
@property(nonatomic, copy) NSString * sessionId;
@end

@interface FLTPreparedPaymentRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithEncryptedFields:(NSString *)encryptedFields
    encodedClientMetaInfo:(NSString *)encodedClientMetaInfo;
@property(nonatomic, copy) NSString * encryptedFields;
@property(nonatomic, copy) NSString * encodedClientMetaInfo;
@end

/// The codec used by FLTApi.
NSObject<FlutterMessageCodec> *FLTApiGetCodec(void);

@protocol FLTApi
/// @return `nil` only when `error != nil`.
- (nullable FLTSessionResponse *)createClientSessionRequest:(FLTSessionRequest *)request error:(FlutterError *_Nullable *_Nonnull)error;
- (void)getBasicPaymentItemsRequest:(FLTPaymentContextRequest *)request completion:(void(^)(FLTPaymentContextResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)getPaymentProductRequest:(FLTGetPaymentProductRequest *)request completion:(void(^)(FLTPaymentProduct *_Nullable, FlutterError *_Nullable))completion;
- (void)preparePaymentRequestRequest:(FLTPaymentRequest *)request completion:(void(^)(FLTPreparedPaymentRequest *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTApi> *_Nullable api);

NS_ASSUME_NONNULL_END
